name: neo_fade_ui
description: "Neo Fade UI - A modern Flutter UI component library"
version: 0.0.1

environment:
  sdk: ^3.10.8
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  mesh_gradient: ^1.3.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
